"""updated device model and enum usage

Revision ID: 1feb388e90c0
Revises: 66abdf18ee1a
Create Date: 2024-09-26 01:06:55.648211

"""
from alembic import op
import sqlalchemy as sa
import flask_security


# revision identifiers, used by Alembic.
revision = '1feb388e90c0'
down_revision = '66abdf18ee1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter_type', sa.String(length=255), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=64), nullable=True))
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('password')
        batch_op.drop_column('record_id')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('parameter_type')

    # ### end Alembic commands ###
