"""updated record_id type

Revision ID: 5442a95e0e9d
Revises: 1feb388e90c0
Create Date: 2024-09-26 01:12:44.248137

"""
from alembic import op
import sqlalchemy as sa
import flask_security


# revision identifiers, used by Alembic.
revision = '5442a95e0e9d'
down_revision = '1feb388e90c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
