"""non-nullable access-level by server

Revision ID: 66abdf18ee1a
Revises: 12cddb8b3f49
Create Date: 2024-09-24 01:30:20.334064

"""
from alembic import op
import sqlalchemy as sa
import flask_security


# revision identifiers, used by Alembic.
revision = '66abdf18ee1a'
down_revision = '12cddb8b3f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.Enum('STUDENT', 'TEACHER'), server_default='STUDENT', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('access_level')

    # ### end Alembic commands ###
