"""updated device creds

Revision ID: fd8df2c3b344
Revises: 5442a95e0e9d
Create Date: 2024-09-26 02:13:11.887762

"""
from alembic import op
import sqlalchemy as sa
import flask_security


# revision identifiers, used by Alembic.
revision = 'fd8df2c3b344'
down_revision = '5442a95e0e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=64), nullable=True))

    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.drop_column('record_id')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('record_id', sa.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
